module.exports = {
  rules: {
    '@tkww-assistant/hierarchical-import-order': 2,
    '@tkww-assistant/lodash-named-imports': 2,
    '@tkww-assistant/member-delimiter-style': 2,
    '@tkww-assistant/redux-action-creator-definitions': 2,
    '@tkww-assistant/redux-action-creator-filenames': 2,
    '@tkww-assistant/redux-action-creator-return': 2,
    '@tkww-assistant/redux-action-creator-type': 2,
    '@tkww-assistant/redux-action-types': 2,
    '@tkww-assistant/redux-state-statements': 2,
    '@tkww-assistant/redux-state-file-naming': 2,
    '@tkww-assistant/redux-thunks-no-default-export': 2,
    '@tkww-assistant/redux-thunks-return-type': 2,
    '@tkww-assistant/redux-thunks-should-dispatch': 2,
    '@tkww-assistant/redux-namespace-members': 2,
    '@tkww-assistant/tuple-spacing': 2,
    '@tkww-assistant/type-declaration-length': 2,
    '@tkww-assistant/type-definition-delimiter-style': 2,
    '@tkww-assistant/type-delimiter-style': 2,
  },
};
