service: auth
app: auth
org: tkwwassistant

disabledDeprecations:
  CLI_OPTIONS_SCHEMA
frameworkVersion: '2.39.2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  githubOAuth:
    handler: handler.githubOAuth
    events:
      - http: 
          path: github-oauth
          method: get
  jiraOAuth:
    handler: handler.jiraOAuth
    events:
      - http: 
          path: jira-oauth
          method: get
  jiraRefresh:
    handler: handler.jiraRefresh
    events:
      - http: 
          path: jira-refresh
          method: get
custom:
  serverless-offline:
    httpPort: 3000
